name: CSV Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  csv-lint:
    name: CSV Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Strip quotes from TSV files
        # Remove all single quotes from any .tsv files so the linter won't fail on unknown delimiters
        run: |
          find ./src/main/resources -type f -name '*.tsv' -exec sed -i "s/'//g" {} +

      - name: csvlinter
        uses: kcheriyath/csvlinter@V0.6.0
        with:
          find_pattern: "*.tsv"
          find_path: "./src/main/resources"
          extra_params: "--delimiter='\t' -lazyquotes"