name: CSV Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  csv-lint:
    name: CSV Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: csvlinter
        uses: kcheriyath/csvlinter@V0.6.0
        with:
          find_pattern: "*.tsv"
          find_path: "./src/main/resources"
          extra_params: "--delimiter='\t'"